#!/bin/bash

cd "$(dirname "$0")"

APP_NAME="rhids"

# Install Java 8 (if not installed)
if ! type java > /dev/null; then
    apt-get install -y software-properties-common
    add-apt-repository -y ppa:webupd8team/java
    apt-get update
    echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
    echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
    apt-get install -y oracle-java8-installer
fi

# Install Gradle
if ! type gradle > /dev/null; then
  add-apt-repository -y ppa:cwchien/gradle
  apt-get update
  apt-get install -y gradle-2.4
fi

# Build and install project
gradle clean && gradle createJar && cp build/libs/*.jar $APP_NAME/$APP_NAME.jar
cp -r $APP_NAME /usr/bin
sed -i "/^PATH/s/\"$/:\/usr\/bin\/$APP_NAME\"/g" /etc/environment
mkdir /var/log/$APP_NAME
