#!/bin/bash

cd "$(dirname "$0")"

APP_NAME="rhids"

# Install Java 8 (if not installed)
if ! type java > /dev/null; then
  apt install -y default-jre
fi

# Build and install project
./gradlew createJar && cp build/libs/*.jar $APP_NAME/$APP_NAME.jar
cp -r $APP_NAME/* /usr/bin
mkdir /var/log/$APP_NAME
