#!/bin/bash

# Install Oracle Java 8 (if not installed)
if ! type java > /dev/null; then
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:webupd8team/java && \
    apt-get update && \
    echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections && \
    echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections && \
    apt-get install -y oracle-java8-installer
fi

java -jar classifier.jar -v 2 -e 1000 -t 0.99 -d 10 -i $1 | tee output.log
